const nodemailer = require('nodemailer');

// Ethereal Email test account (dynamically generated or hardcoded for ease)
// To view sent emails, you can log in to ethereal.email using these credentials
const SMTP_CONFIG = {
  host: 'smtp.ethereal.email',
  port: 587,
  auth: {
    user: 'gregorio.mcclure90@ethereal.email',
    pass: '1Yy1Nq8Sj8P3eH3fQ6'
  }
};


const transporter = nodemailer.createTransport(SMTP_CONFIG);

async function sendHazardAlert(alertMessage, recommendation, primaryRoute, safeRoute) {
  try {
    const hazardHTML = `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #dc2626; color: white; padding: 20px; text-align: center;">
          <h2 style="margin: 0;">🚨 CRITICAL HAZARD ALERT 🚨</h2>
          <p style="margin: 5px 0 0 0; font-size: 14px;">Seven Sisters AI Routing System</p>
        </div>
        <div style="padding: 20px;">
          <h3 style="color: #dc2626;">Primary Route Blocked</h3>
          <p><strong>Route:</strong> ${primaryRoute.name}</p>
          <p style="background-color: #fee2e2; border-left: 4px solid #dc2626; padding: 10px; font-weight: bold;">
            ${alertMessage}
          </p>
          
          <h3 style="color: #059669; margin-top: 25px;">Recommended Action</h3>
          <p style="background-color: #d1fae5; border-left: 4px solid #059669; padding: 10px; font-weight: bold;">
            ${recommendation}
          </p>
          
          ${safeRoute.isSafe ? `
            <p><strong>Suggested Safe Detour:</strong> ${safeRoute.name}</p>
            <p><strong>Estimated Travel Time:</strong> ${safeRoute.estTimeMinutes} mins</p>
          ` : ''}
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; text-align: center;">
            <p>This is an automated alert generated by the Smart Logistics Hazard Prediction Engine.</p>
          </div>
        </div>
      </div>
    `;

    const info = await transporter.sendMail({
      from: '"AI Routing Engine" <your.email@gmail.com>',
      to: 'fleet-manager@smartlogistics.com', // Dummy recipient
      subject: '🚨 CRITICAL: Landslide / Flood Hazard Detected on Route',
      html: hazardHTML
    });

    console.log('------------------------------------------------------');
    console.log('✉️ EMAIL ALERT SENT SUCCESSFULLY!');
    console.log('Preview URL: ' + nodemailer.getTestMessageUrl(info));
    console.log('------------------------------------------------------');

  } catch (error) {
    console.error('Failed to send email alert:', error);
  }
}

async function sendWelcomeEmail(userEmail, userName, activeHazards) {
  try {
    let hazardsHTML = '';

    if (activeHazards && activeHazards.length > 0) {
      const hazardItems = activeHazards.map(h =>
        `<li style="margin-bottom: 8px;">
          <strong>${h.name} (${h.corridor}):</strong> ${h.hazardType} risk. ${h.advisory}
        </li>`
      ).join('');

      hazardsHTML = `
        <div style="background-color: #fee2e2; border-left: 4px solid #dc2626; padding: 15px; margin-top: 20px;">
          <h3 style="color: #dc2626; margin-top: 0;">⚠️ Active Regional Hazards Alert</h3>
          <p style="margin-bottom: 10px; font-size: 14px;">Please be advised of the following critical disruptions currently active in the network:</p>
          <ul style="font-size: 13px; color: #7f1d1d; padding-left: 20px;">
            ${hazardItems}
          </ul>
          <p style="font-size: 12px; margin-bottom: 0;">Check your dashboard for live safe-routing alternatives.</p>
        </div>
      `;
    }

    const emailHTML = `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #0f172a; color: white; padding: 20px; text-align: center;">
          <h2 style="margin: 0; color: #38bdf8;">Welcome to Smart Logistics</h2>
          <p style="margin: 5px 0 0 0; font-size: 14px; color: #94a3b8;">Seven Sisters AI Routing System</p>
        </div>
        <div style="padding: 20px;">
          <p>Hi <strong>${userName}</strong>,</p>
          <p>Your registration was successful. You are now subscribed to the Smart Logistics Network.</p>
          <p>Our AI engines are continuously monitoring terrain, weather, and fleet telemetry to ensure your cargo arrives safely.</p>
          
          ${hazardsHTML}
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; text-align: center;">
            <p>This is an automated message generated by the Smart Logistics Platform.</p>
          </div>
        </div>
      </div>
    `;

    const info = await transporter.sendMail({
      from: '"Smart Logistics Network" <your.email@gmail.com>',
      to: userEmail,
      subject: activeHazards && activeHazards.length > 0
        ? `Welcome to Smart Logistics (⚠️ Active Hazards in Network)`
        : `Welcome to Smart Logistics`,
      html: emailHTML
    });

    console.log('------------------------------------------------------');
    console.log(`✉️ WELCOME EMAIL SENT TO ${userEmail}!`);
    console.log('Preview URL: ' + nodemailer.getTestMessageUrl(info));
    console.log('------------------------------------------------------');

  } catch (error) {
    console.error('Failed to send welcome email:', error);
  }
}

module.exports = {
  sendHazardAlert,
  sendWelcomeEmail
};
